[workspace]
resolver = "2"
members = [ "bin","circuits", "crates/p256-ecdsa"]

[patch."https://github.com/axiom-crypto/halo2-lib.git"]
halo2-base = { path = "../halo2-lib-secp256r1/halo2-base/" }
halo2-ecc = { path = "../halo2-lib-secp256r1/halo2-ecc/" }
