[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snark-verifier-sdk = { git = "https://github.com/axiom-crypto/snark-verifier.git", features = [
  "revm",
] }
